# Generated by Django 4.2.4 on 2023-09-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('end_year', models.CharField(max_length=200)),
                ('intensity', models.IntegerField(max_length=200)),
                ('sector', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('insight', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('start_year', models.CharField(max_length=200)),
                ('impact', models.CharField(max_length=200)),
                ('added', models.CharField(max_length=200)),
                ('published', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('relevance', models.IntegerField(max_length=100)),
                ('pestle', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('likelihood', models.IntegerField(max_length=100)),
            ],
        ),
    ]
