# Generated by Django 4.2.4 on 2023-09-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lumina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='intensity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='likelihood',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='relevance',
            field=models.IntegerField(),
        ),
    ]
