# Generated by Django 4.2.4 on 2023-09-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lumina', '0002_alter_company_intensity_alter_company_likelihood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='end_year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='impact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='start_year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
