# Generated by Django 4.2.4 on 2023-09-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lumina', '0003_alter_company_country_alter_company_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='likelihood',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
